### ISSUE TITLE
Dynamic dictionary of products when adding a new item.

### ISSUE THREAD

**Issue by CarlHejlesen** [TheCodeCrusaders/MealMate#26]
Requirements.
Will be intergrated in item tracing list.
Will be able to scan json file, to look if item is currently know to the system, if not it should be added.
User should then have the option to add things from the community list.
This should only be for the privates users
Properties:
Can it be frozen,
Can it be on the shelf.
Kaloris,
Addd more properties

**Comment by DeeKahy** [comment]
need to disable browsers autocomplete

**Comment by JeppesGithub** [comment]
Item tracking needs to be updated to include standardized properties the user can select when adding new items:

E.g:
- Can it be frozen,
- Can it be on the shelf.
- Kalories,
- Addd more properties

Also, disable browser native auto-complete

**Comment by JeppesGithub** [comment]
**Additional revisions:**

1. item page. the add item button isnt pretty and visible enough. (maybe a little bigger and an icon)
2. add item page looks horrible
3. import to personal item list is a stupid name and should just be "add" or "add to item list"
4. wasted and consumed is good idea (but making them into one that allows amount wasted is better)
5. give sorting ability (sort after what expires the fastest and sort after recently added)
6. big i and big t in the name item tracking on the page as the card header,

**Comment by DeeKahy** [comment]
>    add item page looks horrible
where you submit the new items doesnt fit with the ui design of the reft of the program and has to be updated to look better and not like a bootleg submit menu.

**Comment by CarlHejlesen** [comment]
Struktur

Step 1
Aller først, skal der opretes en json fil igennem registrer feturen. Den skal opertes i users/carl/Privteitemlist.json

Step 2
Næste ting, når er oprettes en ting i systemet, ved item trafficking, ønsker vi at scanne helle global item liste igennem og userens egen liste.

Step 3
Hvis ikke den så eksistere, skal der poppe op om man ikke vil hjælpe med at tilføje propriernes til den item. 

Protein pr 100gram
Kulhydrater pr 100gram
Fedt pr 100 gram
Co2 pr kg 
Kalorier
Hvor det skal opbevares

Step 4
Når den så bliver tilføjet skal den så blive skudt ind i priveteitemlist.json på dette format

{
                "name": "Beef, mince, 5-10% fat, raw",
                "calories per 100 gram": "143",
                "co2 per 1kg": "34,19",
                "protein pr 100 gram": "9,5",
                "carbohydrate pr 100 gram": "0",
                "fat pr 100 gram": "19,5"
 },

**Comment by CarlHejlesen** [comment]
Struktur

Step 1   [Done]
Først skal der tilføjes en funtion som opretter en json fil til den gældene user, Denne bliver lagt så User/Carl/Private_item_property_list.json

Step 1,1
Find ud af hvordan item tracker fungerer.  Næsten umuligt
Step 1,2 [Done]
sæt en API op for at hente userens  Private_item_property_list.json 
Step 1,3  [Done]
Impoter Private_item_property_list.json til public, og sørg for at den er nem at arbejde videre med.
Step 1,4 [done]
Gør så Private_item_property_list.json også bliver printet sammen med user items. [Done] (mangler at den også updater uden at skulle f5)
Step 1,4,1

Step 1,5 [Done]
Inkluder Private_item_property_list.json i auto udfyld functionen.


Step 2 [done]
Tilføj feture til itemtracking så den ikke kun scanner kendte items fra global_item_list igennem, men også den specifikke users Private_item_property_list.json

Step 3 [Done]
Hvis den item der ikke er skrevet i indput boksen hverken eksitere i global_item_list Eller Private_item_property_list.json, så skal der komme en box/knap som giver en forespørgsel til at tilføje properties til denne item.


[Done]
Jeg vil tilføje en rollebar med properties, vil indeholde disse
-Protein pr 100gram
-Kulhydrater pr 100gram
-Fedt pr 100 gram
-Co2 pr kg
-Kalorier

Step 4    [Done]
Når den så bliver tilføjet skal den så blive skudt ind i Private_item_property_list.json på dette format.
{
"name": "Beef, mince, 5-10% fat, raw",
"calories per 100 gram": "143",
"co2 per 1kg": "34,19",
"protein pr 100 gram": "9,5",
"carbohydrate pr 100 gram": "0",
"fat pr 100 gram": "19,5"
},

Step 5 [Not Done]
Css, Det hele virker men det er ikke pænt på nogen måde.

Step 6 
Tilføj en måde at folk kan slette eller ændre i private properties, 
Eller tilføje deres egne properties til allerede eksisterende items fra global listen

**Comment by CarlHejlesen** [comment]
****

**Comment by CarlHejlesen** [comment]
### Bug List 

 **Properties** 
man lige har lavet/gemt kan først slettes efter man har reloaded page.

### Fetures der ikke blev added

**Søgemaskinenen** virker ikke.

**Comment by DeeKahy** [comment]
bug in /pproterties try updating from main and make a new pull request
