### ISSUE TITLE
Shoppinglist

### ISSUE THREAD

**Issue by mathiaszip** [TheCodeCrusaders/MealMate#47]
Shoppinglist:

To-do list:

- Add shopping list page
- Add shopping list to nav bar
- Make a table with name
> Must have a name with a button called “Bought”, this button should prompt the user to select
where the item is located and the expiration date. Upon submit the item would be added to your item list.

> Must have a delete button

> The table should also have a column with prices for each item on the list (using sallinggroup API)

> The prices would load upon reload of the page or when the user adds a new item the function fetching the prices would run again.

> There must also be a total price estimation on all the items combined on the button. The functionality will be the same as on the individual items.

- Setup CSS

**Comment by AlliasGhorbani** [comment]
NEW:
- Display amount of mass of food
- be able to change the grams upon adding 
- add fix add items
