### ISSUE TITLE
Listofrecipes.json improvement

### ISSUE THREAD

**Issue by AlliasGhorbani** [TheCodeCrusaders/MealMate#58]
currently adding more recipes and more properties which include;
- food_class
   - dinner
   - breakfast
   - lunch
- serving size
- preperation time
- 5-10 additional recipes for each foodclass

WIP in Shoppinglist_allias branch

properties will be help to show our first filter settings.
-AG

**Comment by DeeKahy** [comment]
@AlliasGhorbani status?

**Comment by AlliasGhorbani** [comment]
will be added before monday
@DeeKahy
